version: "2"
services:
  app:
    command: "yarn start"
    build:
      context: .
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: always
    container_name: rmi
